2022-07-21 10:35:43,313 INFO: Microblog startup [in /Users/mehultyagi/Check/microblog/app/__init__.py:52]
2022-07-21 10:35:50,277 ERROR: Exception on /edit_profile [GET] [in /Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/app.py:1449]
Traceback (most recent call last):
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/mehultyagi/Check/microblog/app/routes.py", line 89, in edit_profile
    form = EditProfileForm(current_user.username)
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/mehultyagi/Check/microblog/app/forms.py", line 44, in __init__
    super(EditProfileForm, self).__init__(formdata, **kwargs)
NameError: name 'formdata' is not defined
2022-07-21 10:36:09,851 ERROR: Exception on /edit_profile [GET] [in /Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/app.py:1449]
Traceback (most recent call last):
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/mehultyagi/Check/microblog/app/routes.py", line 89, in edit_profile
    form = EditProfileForm(current_user.username)
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/mehultyagi/Check/microblog/app/forms.py", line 44, in __init__
    super(EditProfileForm, self).__init__(formdata, **kwargs)
NameError: name 'formdata' is not defined
2022-07-21 10:38:15,237 INFO: Microblog startup [in /Users/mehultyagi/Check/microblog/app/__init__.py:52]
2022-07-21 17:46:29,690 INFO: Microblog startup [in /Users/mehultyagi/Check/microblog/app/__init__.py:52]
2022-07-21 17:46:46,443 INFO: Microblog startup [in /Users/mehultyagi/Check/microblog/app/__init__.py:52]
2022-07-21 18:41:17,720 INFO: Microblog startup [in /Users/mehultyagi/Check/microblog/app/__init__.py:52]
2022-07-21 19:08:57,830 INFO: Microblog startup [in /Users/mehultyagi/Check/microblog/app/__init__.py:52]
2022-07-21 19:09:28,049 INFO: Microblog startup [in /Users/mehultyagi/Check/microblog/app/__init__.py:52]
2022-07-22 18:56:19,646 INFO: Microblog startup [in /Users/mehultyagi/Check/microblog/app/__init__.py:52]
2022-07-22 19:26:32,104 INFO: Microblog startup [in /Users/mehultyagi/Check/microblog/app/__init__.py:52]
2022-07-22 19:27:22,091 ERROR: Exception on /user/Whale [GET] [in /Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/app.py:1449]
Traceback (most recent call last):
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/mehultyagi/Check/microblog/app/routes.py", line 84, in user
    return render_template("user.html", user=user, posts=posts, form=form)
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/mehultyagi/Check/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/mehultyagi/Check/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %} {% endblock %}
  File "/Users/mehultyagi/Check/microblog/app/templates/user.html", line 21, in block 'content'
    {{ form.hidden_tag() }}
TypeError: hidden_tag() missing 1 required positional argument: 'self'
2022-07-22 19:28:24,055 INFO: Microblog startup [in /Users/mehultyagi/Check/microblog/app/__init__.py:52]
2022-07-22 19:28:39,047 ERROR: Exception on /user/Whale [GET] [in /Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/app.py:1449]
Traceback (most recent call last):
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/mehultyagi/Check/microblog/app/routes.py", line 84, in user
    return render_template("user.html", user=user, posts=posts, form=form)
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/mehultyagi/Check/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/mehultyagi/Check/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %} {% endblock %}
  File "/Users/mehultyagi/Check/microblog/app/templates/user.html", line 27, in block 'content'
    <form action="{{ url_for('unollow', username=user.username) }}" method="post">
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'unollow' with values ['username']. Did you mean 'unfollow' instead?
2022-07-22 19:30:36,875 INFO: Microblog startup [in /Users/mehultyagi/Check/microblog/app/__init__.py:52]
2022-07-23 11:23:57,138 INFO: Microblog startup [in /Users/mehultyagi/Check/microblog/app/__init__.py:52]
2022-07-23 11:30:42,771 INFO: Microblog startup [in /Users/mehultyagi/Check/microblog/app/__init__.py:52]
